kind: Pod
apiVersion: v1
metadata:
  name: origin-pod
spec:
  volumes:
    - name: origin-vol
      persistentVolumeClaim:
        claimName: pvc1
  containers:
    - name: main-ctr
      image: ubuntu
      command:
      - /bin/bash
      - "-c"
      - "sleep 60m"
      volumeMounts:
      - mountPath: /data
        name: origin-vol