apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: my_local_web_server
spec:
#We can define more than one containers, but a good practice is to define only one
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80